
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 31 22:42:39 CET 2020
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Thu Dec 31 22:42:39 CET 2020
  */
public class MPParser_error_recovery extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser_error_recovery() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser_error_recovery(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\105\000\002\003\005\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\005\000\002\004\005" +
    "\000\002\004\005\000\002\005\003\000\002\006\005\000" +
    "\002\006\003\000\002\007\006\000\002\007\006\000\002" +
    "\007\005\000\002\007\004\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\011\005\000\002\011\003" +
    "\000\002\012\003\000\002\012\003\000\002\013\012\000" +
    "\002\013\012\000\002\013\011\000\002\013\010\000\002" +
    "\013\007\000\002\013\006\000\002\013\005\000\002\013" +
    "\004\000\002\014\005\000\002\014\003\000\002\015\003" +
    "\000\002\015\003\000\002\015\006\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\017\005\000\002" +
    "\017\005\000\002\017\004\000\002\020\006\000\002\020" +
    "\006\000\002\020\003\000\002\021\005\000\002\021\003" +
    "\000\002\022\007\000\002\022\007\000\002\022\005\000" +
    "\002\022\003\000\002\023\004\000\002\024\003\000\002" +
    "\025\005\000\002\025\003\000\002\026\011\000\002\026" +
    "\011\000\002\026\007\000\002\026\005\000\002\026\003" +
    "\000\002\027\004\000\002\027\004\000\002\027\003\000" +
    "\002\030\003\000\002\030\003\000\002\031\004\000\002" +
    "\031\004\000\002\031\003\000\002\032\005\000\002\032" +
    "\005\000\002\032\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\006\003\004\004\005\001\002\000\004\002" +
    "\ufffe\001\002\000\006\003\012\010\010\001\002\000\004" +
    "\002\007\001\002\000\004\002\000\001\002\000\006\003" +
    "\160\016\161\001\002\000\012\003\ufffa\006\ufffa\007\156" +
    "\010\ufffa\001\002\000\006\006\024\010\020\001\002\000" +
    "\012\003\ufff8\006\ufff8\007\ufff8\010\ufff8\001\002\000\010" +
    "\003\021\006\024\010\020\001\002\000\006\003\016\005" +
    "\017\001\002\000\004\002\uffff\001\002\000\004\002\001" +
    "\001\002\000\006\003\143\015\144\001\002\000\006\003" +
    "\030\022\031\001\002\000\012\003\uffef\007\uffef\022\uffef" +
    "\040\uffef\001\002\000\012\003\uffee\007\uffee\022\uffee\040" +
    "\uffee\001\002\000\006\003\116\035\117\001\002\000\012" +
    "\003\uffed\007\uffed\022\uffed\040\uffed\001\002\000\010\003" +
    "\030\007\027\022\031\001\002\000\006\006\024\010\020" +
    "\001\002\000\006\003\uffd7\005\uffd7\001\002\000\006\003" +
    "\033\027\035\001\002\000\006\003\ufffd\005\ufffd\001\002" +
    "\000\010\003\uffc8\007\uffc8\024\uffc8\001\002\000\010\003" +
    "\073\007\072\024\075\001\002\000\006\003\041\031\037" +
    "\001\002\000\010\003\uffcd\007\uffcd\024\uffcd\001\002\000" +
    "\006\003\071\010\070\001\002\000\006\003\043\041\042" +
    "\001\002\000\006\003\uffc5\041\uffc5\001\002\000\010\003" +
    "\047\010\044\011\045\001\002\000\010\003\uffc9\007\uffc9" +
    "\024\uffc9\001\002\000\034\003\uffe2\007\uffe2\012\uffe2\013" +
    "\uffe2\014\uffe2\016\062\022\uffe2\025\uffe2\033\uffe2\034\uffe2" +
    "\036\uffe2\040\uffe2\041\uffe2\001\002\000\032\003\uffe1\007" +
    "\uffe1\012\uffe1\013\uffe1\014\uffe1\022\uffe1\025\uffe1\033\uffe1" +
    "\034\uffe1\036\uffe1\040\uffe1\041\uffe1\001\002\000\006\003" +
    "\uffc4\041\uffc4\001\002\000\006\003\uffc3\041\uffc3\001\002" +
    "\000\006\003\052\041\051\001\002\000\006\003\054\032" +
    "\055\001\002\000\010\003\uffca\007\uffca\024\uffca\001\002" +
    "\000\006\003\060\030\061\001\002\000\006\003\uffc0\030" +
    "\uffc0\001\002\000\006\003\057\010\056\001\002\000\006" +
    "\003\uffc2\030\uffc2\001\002\000\006\003\uffc1\030\uffc1\001" +
    "\002\000\010\003\uffcb\007\uffcb\024\uffcb\001\002\000\010" +
    "\003\uffcc\007\uffcc\024\uffcc\001\002\000\010\017\063\020" +
    "\065\021\066\001\002\000\006\003\ufff3\007\ufff3\001\002" +
    "\000\004\003\067\001\002\000\006\003\ufff2\007\ufff2\001" +
    "\002\000\006\003\ufff1\007\ufff1\001\002\000\032\003\uffe0" +
    "\007\uffe0\012\uffe0\013\uffe0\014\uffe0\022\uffe0\025\uffe0\033" +
    "\uffe0\034\uffe0\036\uffe0\040\uffe0\041\uffe0\001\002\000\006" +
    "\003\uffc7\041\uffc7\001\002\000\006\003\uffc6\041\uffc6\001" +
    "\002\000\006\003\033\027\035\001\002\000\010\003\uffd1" +
    "\007\uffd1\023\uffd1\001\002\000\010\003\uffd5\007\uffd5\023" +
    "\uffd5\001\002\000\004\026\104\001\002\000\010\003\100" +
    "\007\077\023\101\001\002\000\006\003\073\024\075\001" +
    "\002\000\006\003\uffd8\005\uffd8\001\002\000\006\003\uffd9" +
    "\005\uffd9\001\002\000\010\003\uffd6\007\uffd6\023\uffd6\001" +
    "\002\000\006\003\107\041\106\001\002\000\004\010\105" +
    "\001\002\000\006\003\uffd0\041\uffd0\001\002\000\006\010" +
    "\044\011\045\001\002\000\010\003\uffd2\007\uffd2\023\uffd2" +
    "\001\002\000\006\003\uffcf\025\uffcf\001\002\000\006\003" +
    "\113\025\112\001\002\000\010\003\uffd4\007\uffd4\023\uffd4" +
    "\001\002\000\010\003\uffd3\007\uffd3\023\uffd3\001\002\000" +
    "\010\003\uffce\007\uffce\024\uffce\001\002\000\012\003\ufff0" +
    "\007\ufff0\022\ufff0\040\ufff0\001\002\000\012\003\uffe5\007" +
    "\uffe5\022\uffe5\040\uffe5\001\002\000\010\003\122\010\044" +
    "\011\045\001\002\000\006\003\131\036\130\001\002\000" +
    "\014\003\uffe3\012\126\013\125\014\124\036\uffe3\001\002" +
    "\000\012\003\uffe6\007\uffe6\022\uffe6\040\uffe6\001\002\000" +
    "\006\010\044\011\045\001\002\000\006\010\uffdd\011\uffdd" +
    "\001\002\000\006\010\uffde\011\uffde\001\002\000\006\010" +
    "\uffdf\011\uffdf\001\002\000\006\003\uffe4\036\uffe4\001\002" +
    "\000\006\003\132\016\133\001\002\000\012\003\uffe7\007" +
    "\uffe7\022\uffe7\040\uffe7\001\002\000\012\003\uffe8\007\uffe8" +
    "\022\uffe8\040\uffe8\001\002\000\006\003\134\037\135\001" +
    "\002\000\012\003\uffe9\007\uffe9\022\uffe9\040\uffe9\001\002" +
    "\000\010\003\136\006\024\010\020\001\002\000\012\003" +
    "\uffea\007\uffea\022\uffea\040\uffea\001\002\000\010\003\141" +
    "\007\027\040\140\001\002\000\012\003\uffec\007\uffec\022" +
    "\uffec\040\uffec\001\002\000\012\003\uffeb\007\uffeb\022\uffeb" +
    "\040\uffeb\001\002\000\006\003\ufffb\005\ufffb\001\002\000" +
    "\012\003\uffda\007\uffda\022\uffda\040\uffda\001\002\000\010" +
    "\003\146\010\044\011\045\001\002\000\016\003\uffbd\007" +
    "\uffbd\022\uffbd\033\uffbd\034\uffbd\040\uffbd\001\002\000\012" +
    "\003\uffdb\007\uffdb\022\uffdb\040\uffdb\001\002\000\016\003" +
    "\uffdc\007\uffdc\022\uffdc\033\150\034\151\040\uffdc\001\002" +
    "\000\006\010\044\011\045\001\002\000\006\010\044\011" +
    "\045\001\002\000\016\003\uffbe\007\uffbe\022\uffbe\033\uffbe" +
    "\034\uffbe\040\uffbe\001\002\000\016\003\uffbf\007\uffbf\022" +
    "\uffbf\033\uffbf\034\uffbf\040\uffbf\001\002\000\010\003\030" +
    "\007\027\022\031\001\002\000\006\003\ufffc\005\ufffc\001" +
    "\002\000\004\010\010\001\002\000\012\003\ufff9\006\ufff9" +
    "\007\ufff9\010\ufff9\001\002\000\012\003\ufff4\006\ufff4\007" +
    "\ufff4\010\ufff4\001\002\000\012\003\163\017\063\020\065" +
    "\021\066\001\002\000\006\003\165\007\164\001\002\000" +
    "\012\003\ufff5\006\ufff5\007\ufff5\010\ufff5\001\002\000\012" +
    "\003\ufff7\006\ufff7\007\ufff7\010\ufff7\001\002\000\012\003" +
    "\ufff6\006\ufff6\007\ufff6\010\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\004\003\005\001\001\000\002\001\001\000" +
    "\012\004\014\005\013\006\010\007\012\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\011\153\012\021\013\024\017\022\001\001" +
    "\000\002\001\001\000\012\011\025\012\021\013\024\017" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\141\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\020\031\001\001\000\010\012\114\013" +
    "\024\017\022\001\001\000\002\001\001\000\006\025\033" +
    "\026\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\021\075\022\073\001\001\000\004\027\037\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\045\030\047\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\031\052" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\063\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\026\113\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\023\102\001\001\000\002\001" +
    "\001\000\004\022\101\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\015\107\024\110\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\014\117\015\120\001" +
    "\001\000\002\001\001\000\004\016\122\001\001\000\002" +
    "\001\001\000\004\015\126\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\011\136\012\021\013\024" +
    "\017\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\015\144\032\146\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\015\152" +
    "\001\001\000\004\015\151\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\020\154\001\001\000\002\001\001" +
    "\000\004\007\156\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\161\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser_error_recovery$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser_error_recovery$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser_error_recovery$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




   public int errNo = 0;

   public static void main( String[] args )
   {
      try
	  {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new MPLexer( file );
		   MPParser_error_recovery parser = new MPParser_error_recovery( scanner );
		   parser.parse();
		   if ( parser.errNo == 0 )
		      System.out.println( "Analiza zavrsena. U kodu nema gresaka." );
		   else
		      System.out.println( "Analiza zavrsena. Broj gresaka: " + parser.errNo );
	  }
	  catch( Exception e )
	  {
		   e.printStackTrace();
	  }
   }
   
   public int getLine()
   {
   	  return (( MPLexer) getScanner()).getLine();
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser_error_recovery$actions {
  private final MPParser_error_recovery parser;

  /** Constructor */
  CUP$MPParser_error_recovery$actions(MPParser_error_recovery parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser_error_recovery$do_action(
    int                        CUP$MPParser_error_recovery$act_num,
    java_cup.runtime.lr_parser CUP$MPParser_error_recovery$parser,
    java.util.Stack            CUP$MPParser_error_recovery$stack,
    int                        CUP$MPParser_error_recovery$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser_error_recovery$result;

      /* select the action based on the action number */
      switch (CUP$MPParser_error_recovery$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // Expression ::= Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat izraz");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(24/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Expression ::= Expression MUL Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato mnoÅ¾enje");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(24/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Expression ::= Expression PLUS Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato sabiranje");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(24/*Expression*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // Mapping ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan executedOn");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(23/*Mapping*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Mapping ::= EXECUTEDON error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan identifikator kod definicije mapiranja");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(23/*Mapping*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Mapping ::= EXECUTEDON ID 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato mapiranje");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(23/*Mapping*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Demand ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivana definicija zahteva");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(22/*Demand*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Demand ::= Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat zahtev");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(22/*Demand*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // TaskName ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekuje se taskId");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(21/*TaskName*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // TaskName ::= TASKID error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan identifikator kod definicije imena posla");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(21/*TaskName*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // TaskName ::= TASKID ID 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato imenovanje posla");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(21/*TaskName*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // TaskDef ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan task");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(20/*TaskDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // TaskDef ::= TASK TaskName error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekuje se ',' pre definicije bloka zahteva");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(20/*TaskDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // TaskDef ::= TASK TaskName COMMA Demand error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekuje se ',' pre definicije mapiranja");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(20/*TaskDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // TaskDef ::= TASK TaskName COMMA Demand COMMA Mapping error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan ~task");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(20/*TaskDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // TaskDef ::= TASK TaskName COMMA Demand COMMA Mapping TASKEND 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata definicija posla");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(20/*TaskDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // TaskList ::= TaskDef 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata lista poslova");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(19/*TaskList*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // TaskList ::= TaskList SEMICOLON TaskDef 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata lista poslova");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(19/*TaskList*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Capacity ::= Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato definisanje kapaciteta servera");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(18/*Capacity*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ServerName ::= SERVERID ID 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato imenovanje servera");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(17/*ServerName*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // ServerDef ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan server");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(16/*ServerDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // ServerDef ::= SERVER ServerName error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekuje se ',' pre definicije kapaciteta");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(16/*ServerDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // ServerDef ::= SERVER ServerName COMMA Capacity error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan ~server");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(16/*ServerDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // ServerDef ::= SERVER ServerName COMMA Capacity SERVEREND 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata definicija servera");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(16/*ServerDef*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // ServerList ::= ServerDef 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata lista servera");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(15/*ServerList*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // ServerList ::= ServerList SEMICOLON ServerDef 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata lista servera");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(15/*ServerList*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Deployment ::= error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan deployment");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(14/*Deployment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Deployment ::= DEPLOYMENT TaskList ServerList error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan ~deloyment");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(14/*Deployment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Deployment ::= DEPLOYMENT TaskList ServerList DEPLOYMENTEND 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat deployment");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(14/*Deployment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Assignment ::= ID error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekuje se ':='");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(13/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Assignment ::= ID ASSIGN error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan izraz sa desne strane dodele");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(13/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Assignment ::= ID ASSIGN Expression 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata dodela");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(13/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // RelOp ::= GREATER 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat relacioni operator greater");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(12/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // RelOp ::= EQUAL 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat relacioni operator equal");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(12/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // RelOp ::= LESS 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat relacioni operator less");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(12/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Term ::= ID COLON Type error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivana konstanta ili identifikator");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(11/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Term ::= CONST 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata konstanta");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(11/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Term ::= ID 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat identifikator");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(11/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RelExpression ::= Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat izraz");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(10/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat izraz");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(10/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // WhileStatement ::= WHILE error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano '('");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // WhileStatement ::= WHILE LEFTPAR error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan logiÄ?ki izraz");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // WhileStatement ::= WHILE LEFTPAR RelExpression error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano ')'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // WhileStatement ::= WHILE LEFTPAR RelExpression RIGHTPAR error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano ':'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // WhileStatement ::= WHILE LEFTPAR RelExpression RIGHTPAR COLON error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano '{'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // WhileStatement ::= WHILE LEFTPAR RelExpression RIGHTPAR COLON LEFTCURVEDPAR error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan niz naredbi");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // WhileStatement ::= WHILE LEFTPAR RelExpression RIGHTPAR COLON LEFTCURVEDPAR Statements error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano '}'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // WhileStatement ::= WHILE LEFTPAR RelExpression RIGHTPAR COLON LEFTCURVEDPAR Statements RIGHTCURVEDPAR 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata while petlja");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(9/*WhileStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-7)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Statement ::= WhileStatement 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata naredba");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Statement ::= Assignment 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata naredba");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(8/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Statements ::= Statement 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat niz naredbi");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(7/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Statements ::= Statements SEMICOLON Statement 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat niz naredbi");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(7/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= STRING 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat tip string");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Type ::= DOUBLE 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat tip double");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= INTEGER 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznat tip int");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Variable ::= ID error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano ':'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Variable ::= ID COLON error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivan tip promenljive");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Variable ::= ID COLON Type error 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nOÄ?ekivano ';'");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Variable ::= ID COLON Type SEMICOLON 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata deklaracija promenljive");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VariableDeclaration ::= Variable 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznate deklaracije promenljivih");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(4/*VariableDeclaration*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VariableDeclaration ::= VariableDeclaration SEMICOLON Variable 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznate deklaracije promenljivih");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(4/*VariableDeclaration*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Declarations ::= VariableDeclaration 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznata deklaracija");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(3/*Declarations*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Body ::= Declarations error Deployment 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nPre Deployment bloka obavezan blok naredbi ");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(2/*Body*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Body ::= error Statements Deployment 
            {
              Object RESULT = null;
		
             System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nDeklaracije su obavezne na poÄ?etku. ");
             parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(2/*Body*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Body ::= Declarations Statements Deployment 
            {
              Object RESULT = null;
		
            System.out.println("Prepoznato telo modela");
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(2/*Body*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Model ::= error 
            {
              Object RESULT = null;
		
            System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\nMODEL uvek na poÄ?etku. ");
            parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(1/*Model*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Model ::= MODEL Body error 
            {
              Object RESULT = null;
		
            System.out.println("GreÅ¡ka u liniji " + parser.getLine() + ". \r\n~model nedostaje. ");
            parser.errNo++;
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(1/*Model*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Model EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).value;
		RESULT = start_val;
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser_error_recovery$parser.done_parsing();
          return CUP$MPParser_error_recovery$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Model ::= MODEL Body MODELEND 
            {
              Object RESULT = null;
		
        System.out.println("Prepoznate deklaracije promenljivih"); 
        
              CUP$MPParser_error_recovery$result = new java_cup.runtime.Symbol(1/*Model*/, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser_error_recovery$stack.elementAt(CUP$MPParser_error_recovery$top-0)).right, RESULT);
            }
          return CUP$MPParser_error_recovery$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

