
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 31 22:42:39 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TASKEND = 22;
  public static final int SEMICOLON = 5;
  public static final int PLUS = 25;
  public static final int TASK = 21;
  public static final int SERVER = 18;
  public static final int RIGHTCURVEDPAR = 30;
  public static final int EQUAL = 9;
  public static final int WHILE = 4;
  public static final int LEFTPAR = 27;
  public static final int LEFTCURVEDPAR = 29;
  public static final int GREATER = 10;
  public static final int RIGHTPAR = 28;
  public static final int COLON = 12;
  public static final int ID = 6;
  public static final int DEPLOYMENT = 16;
  public static final int SERVERID = 20;
  public static final int STRING = 15;
  public static final int COMMA = 31;
  public static final int TASKID = 23;
  public static final int SERVEREND = 19;
  public static final int EOF = 0;
  public static final int MODELEND = 3;
  public static final int CONST = 7;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int MODEL = 2;
  public static final int INTEGER = 13;
  public static final int MUL = 26;
  public static final int EXECUTEDON = 24;
  public static final int DEPLOYMENTEND = 17;
  public static final int LESS = 8;
  public static final int DOUBLE = 14;
}

