
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 16 20:10:05 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TASKEND = 24;
  public static final int CONSTDOUBLE = 17;
  public static final int SEMICOLON = 5;
  public static final int PLUS = 27;
  public static final int TASK = 23;
  public static final int CONSTSTRING = 15;
  public static final int SERVER = 20;
  public static final int RIGHTCURVEDPAR = 32;
  public static final int EQUAL = 7;
  public static final int WHILE = 4;
  public static final int LEFTPAR = 29;
  public static final int LEFTCURVEDPAR = 31;
  public static final int GREATER = 8;
  public static final int RIGHTPAR = 30;
  public static final int COLON = 10;
  public static final int DEPLOYMENT = 18;
  public static final int ID = 14;
  public static final int SERVERID = 22;
  public static final int STRING = 13;
  public static final int COMMA = 33;
  public static final int TASKID = 25;
  public static final int SERVEREND = 21;
  public static final int EOF = 0;
  public static final int MODELEND = 3;
  public static final int error = 1;
  public static final int CONSTINTEGER = 16;
  public static final int ASSIGN = 9;
  public static final int MODEL = 2;
  public static final int INTEGER = 11;
  public static final int MUL = 28;
  public static final int EXECUTEDON = 26;
  public static final int DEPLOYMENTEND = 19;
  public static final int LESS = 6;
  public static final int DOUBLE = 12;
}

