
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 26 10:56:38 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TASKEND = 16;
  public static final int CONSTDOUBLE = 34;
  public static final int SEMICOLON = 31;
  public static final int CONSTSTRING = 32;
  public static final int PLUS = 23;
  public static final int TASK = 15;
  public static final int SERVER = 12;
  public static final int RIGHTCURVEDPAR = 28;
  public static final int EQUAL = 20;
  public static final int WHILE = 4;
  public static final int LEFTPAR = 25;
  public static final int LEFTCURVEDPAR = 27;
  public static final int GREATER = 21;
  public static final int RIGHTPAR = 26;
  public static final int COLON = 30;
  public static final int ID = 9;
  public static final int DEPLOYMENT = 10;
  public static final int SERVERID = 14;
  public static final int STRING = 8;
  public static final int COMMA = 29;
  public static final int TASKID = 17;
  public static final int SERVEREND = 13;
  public static final int EOF = 0;
  public static final int MODELEND = 3;
  public static final int error = 1;
  public static final int CONSTINTEGER = 33;
  public static final int ASSIGN = 22;
  public static final int MODEL = 2;
  public static final int INTEGER = 6;
  public static final int DEFAULT = 5;
  public static final int MUL = 24;
  public static final int EXECUTEDON = 18;
  public static final int LESS = 19;
  public static final int DEPLOYMENTEND = 11;
  public static final int DOUBLE = 7;
}

