
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 25 23:46:20 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TASKEND = 17;
  public static final int SEMICOLON = 32;
  public static final int PLUS = 24;
  public static final int TASK = 16;
  public static final int SERVER = 13;
  public static final int RIGHTCURVEDPAR = 29;
  public static final int EQUAL = 21;
  public static final int WHILE = 4;
  public static final int LEFTPAR = 26;
  public static final int LEFTCURVEDPAR = 28;
  public static final int GREATER = 22;
  public static final int RIGHTPAR = 27;
  public static final int COLON = 31;
  public static final int ID = 6;
  public static final int DEPLOYMENT = 11;
  public static final int SERVERID = 15;
  public static final int STRING = 10;
  public static final int COMMA = 30;
  public static final int TASKID = 18;
  public static final int SERVEREND = 14;
  public static final int EOF = 0;
  public static final int MODELEND = 3;
  public static final int CONST = 7;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int MODEL = 2;
  public static final int INTEGER = 8;
  public static final int DEFAULT = 5;
  public static final int MUL = 25;
  public static final int EXECUTEDON = 19;
  public static final int LESS = 20;
  public static final int DEPLOYMENTEND = 12;
  public static final int DOUBLE = 9;
}

